#!/bin/bash

echo "🚀 Deploying OCR Demo to Render"
echo "================================"

# Kiểm tra git status
if [ -n "$(git status --porcelain)" ]; then
    echo "⚠️  Có thay đổi chưa commit. Commit trước khi deploy:"
    git status
    echo ""
    echo "Chạy các lệnh sau:"
    echo "git add ."
    echo "git commit -m 'Update OCR demo for Render deployment'"
    echo "git push origin main"
    exit 1
fi

echo "✅ Git repository sạch"

# Kiểm tra render.yaml
if [ ! -f "render.yaml" ]; then
    echo "❌ File render.yaml không tồn tại"
    exit 1
fi

echo "✅ File render.yaml tồn tại"

# Kiểm tra backend Dockerfile
if [ ! -f "backend/Dockerfile" ]; then
    echo "❌ File backend/Dockerfile không tồn tại"
    exit 1
fi

echo "✅ Backend Dockerfile tồn tại"

# Kiểm tra frontend build script
if [ ! -f "frontend/render-build.sh" ]; then
    echo "❌ File frontend/render-build.sh không tồn tại"
    exit 1
fi

echo "✅ Frontend build script tồn tại"

# Kiểm tra environment files
if [ ! -f "frontend/.env.production" ]; then
    echo "❌ File frontend/.env.production không tồn tại"
    exit 1
fi

echo "✅ Production environment file tồn tại"

echo ""
echo "📋 Checklist trước khi deploy:"
echo "1. ✅ Git repository sạch"
echo "2. ✅ render.yaml configured"
echo "3. ✅ Backend Dockerfile ready"
echo "4. ✅ Frontend build script ready"
echo "5. ✅ Environment variables set"
echo ""
echo "🔧 Các bước deploy:"
echo "1. Push code lên GitHub"
echo "2. Connect repository với Render"
echo "3. Configure environment variables"
echo "4. Deploy services"
echo ""
echo "📝 Hướng dẫn chi tiết:"
echo ""
echo "1. Push code:"
echo "   git push origin main"
echo ""
echo "2. Trên Render Dashboard:"
echo "   - Tạo New Web Service cho backend"
echo "   - Tạo New Static Site cho frontend"
echo "   - Connect với GitHub repository"
echo ""
echo "3. Environment Variables (Backend):"
echo "   - NODE_ENV=production"
echo "   - PORT=4000"
echo "   - DATABASE_URL=<your-neon-database-url>"
echo "   - JWT_SECRET=<auto-generated>"
echo "   - FRONTEND_URL=https://restaurant-inventory-frontend.onrender.com"
echo ""
echo "4. Environment Variables (Frontend):"
echo "   - VITE_API_URL=https://restaurant-inventory-backend.onrender.com"
echo "   - VITE_ENV=production"
echo ""
echo "5. Build Commands:"
echo "   Backend: (auto-detect Dockerfile)"
echo "   Frontend: cd frontend && ./render-build.sh"
echo ""
echo "6. Publish Directory (Frontend):"
echo "   ./frontend/dist"
echo ""
echo "🌐 URLs sau khi deploy:"
echo "   Backend: https://restaurant-inventory-backend.onrender.com"
echo "   Frontend: https://restaurant-inventory-frontend.onrender.com"
echo "   OCR Demo: https://restaurant-inventory-frontend.onrender.com/ocr-demo"
echo ""
echo "🔍 Kiểm tra sau deploy:"
echo "   - Backend health: https://restaurant-inventory-backend.onrender.com/api/health"
echo "   - Frontend load: https://restaurant-inventory-frontend.onrender.com"
echo "   - OCR demo: https://restaurant-inventory-frontend.onrender.com/ocr-demo"
echo ""
echo "📞 Troubleshooting:"
echo "   - Kiểm tra Render logs"
echo "   - Verify environment variables"
echo "   - Test API endpoints"
echo "   - Check CORS configuration"
echo ""
echo "✅ Sẵn sàng deploy! Chạy 'git push origin main' để bắt đầu."